I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 197, in script
    if true:
  File "game/script.rpy", line 197, in <module>
    if true:
NameError: name 'true' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 197, in script
    if true:
  File "C:\Users\Grocholx\Desktop\RenPY\renpy-8.2.1-sdk\renpy\ast.py", line 1842, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Grocholx\Desktop\RenPY\renpy-8.2.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Grocholx\Desktop\RenPY\renpy-8.2.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 197, in <module>
    if true:
NameError: name 'true' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
Casino 1.0
Tue May 14 12:57:52 2024
